FROM dhonanhibatullah/bi-digital-twin-app:1.0.1-dev

# Environment variables will be set by Railway
# These are declared here for documentation purposes
ENV APP_HOST=0.0.0.0
ENV APP_PORT=8080
ENV TOKEN_ISSUER=""
ENV TOKEN_PRIVATE_KEY=""
ENV TOKEN_EXPIRATION=12
ENV DB_USERNAME=""
ENV DB_PASSWORD=""
ENV DB_HOST=""
ENV DB_PORT=5432
ENV DB_NAME=""
ENV DB_TIMEOUT_MS=5000
ENV MQTT_BROKER=""
ENV MQTT_CLIENT_ID=bi-dt-mqtt-server
ENV MQTT_USERNAME=""
ENV MQTT_PASSWORD=""

EXPOSE 8080

